---
- name: Build Image and Push to Docker hub
  hosts: ansible-server

  tasks:
  - name: Create docker Image
    command: docker build -t regapp:v1 .
    args:
      chdir: /opt/docker

  - name: Create tag to push image on to dockerhub
    command: docker tag regapp:v1 nkqhub/regapp:latest

  - name: push docker image
    command: docker push nkqhub/regapp:latest
